# Generated by Django 3.1.6 on 2021-02-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('work_stage', models.FloatField(blank=True, null=True)),
                ('salary_preference', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientWork',
            fields=[
                ('client_work_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'client_work',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientWorkPreferences',
            fields=[
                ('client_work_preferences_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'client_work_preferences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scrapper',
            fields=[
                ('scrapper_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('is_deleted', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('name', models.TextField()),
                ('login', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scrapper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacancy_name', models.TextField()),
                ('expirience', models.FloatField(blank=True, null=True)),
                ('effectivness', models.FloatField(blank=True, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('website_name', models.TextField()),
                ('salary', models.FloatField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vacancy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('work_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField()),
            ],
            options={
                'db_table': 'work_category',
                'managed': False,
            },
        ),
    ]
