# Generated by Django 3.1.6 on 2021-02-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('work_stage', models.FloatField(blank=True, null=True)),
                ('salary_preference', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientWork',
            fields=[
                ('client_work_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Клиент - работа',
                'verbose_name_plural': 'Клиенты - работы',
                'db_table': 'client_work',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientWorkPreferences',
            fields=[
                ('client_work_preferences_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Избранные категории клиента',
                'verbose_name_plural': 'Избранные категории клиентов',
                'db_table': 'client_work_preferences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('work_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField()),
            ],
            options={
                'db_table': 'work_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Айди города')),
                ('city_name', models.TextField(verbose_name='Город')),
            ],
        ),
    ]
