# Generated by Django 3.1.6 on 2021-02-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacancy_name', models.TextField()),
                ('expirience', models.FloatField(blank=True, null=True)),
                ('effectivness', models.FloatField(blank=True, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('website_name', models.TextField()),
                ('salary', models.FloatField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vacancy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('work_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField()),
            ],
            options={
                'db_table': 'work_category',
                'managed': False,
            },
        ),
    ]
