# Generated by Django 3.1.6 on 2021-02-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'managed': False, 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterModelOptions(
            name='workcategory',
            options={'managed': False, 'verbose_name': 'Категория работы', 'verbose_name_plural': 'Категории работы'},
        ),
    ]
